In [1]:
arr = [1,2,4]

In [2]:
import numpy as np

In [3]:
np.array(arr)

array([1, 2, 4])

In [4]:
arr_d = [[1,2,3],[4,5,6]]

In [5]:
np.array(arr_d)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [14]:
np.random.rand(5)

array([0.79690576, 0.78777705, 0.87750126, 0.37329054, 0.59047394])

In [16]:
np.random.rand(3,4)

array([[0.98619099, 0.90636667, 0.07647635, 0.56884478],
       [0.70130157, 0.78024919, 0.45654061, 0.62079328],
       [0.56144779, 0.81612965, 0.63621353, 0.00259822]])

In [20]:
np.arange(1,5)

array([1, 2, 3, 4])

In [21]:
np.random.randn(2,3)

array([[ 0.72048896, -1.84913964,  0.01914116],
       [-0.97525354, -0.02409308, -0.36959251]])

In [24]:
np.random.randint(3,200,5)

array([ 62,  95,  78,  89, 109])

In [25]:
newarr = np.random.randint(2,10,10)

In [26]:
newarr

array([9, 6, 2, 3, 8, 7, 6, 9, 8, 9])

In [30]:
n = newarr.reshape(5,2)

In [31]:
n

array([[9, 6],
       [2, 3],
       [8, 7],
       [6, 9],
       [8, 9]])

In [32]:
n.max()

9

In [33]:
n.argmax()

0

In [35]:
n.dtype

dtype('int32')

In [37]:
n.shape

(5, 2)

In [40]:
np.random.randint(1,4,4)

array([1, 1, 1, 3])

In [42]:
np.linspace(1,4,5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [48]:
np.random.randn(4,2)

array([[-0.22502897,  0.94332204],
       [-0.40732642,  0.13617313],
       [ 1.06564043, -0.15383186],
       [ 0.86233134,  0.08328251]])