In [16]:
import numpy as np

In [2]:
a = [1,2,3,9,13,16]

In [3]:
a[1:3]

[2, 3]

In [4]:
a[1:]

[2, 3, 9, 13, 16]

In [5]:
a[:4]

[1, 2, 3, 9]

In [6]:
arr = np.arange(10)

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
 arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
arr_slice = arr[1:8]

In [10]:
arr_slice

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
arr_slice

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr[1,2]

6

In [25]:
arr[1][2]

6

In [26]:
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

In [27]:
arr[1:,]

array([[4, 5, 6],
       [7, 8, 9]])

In [28]:
arr[1:, :2]

array([[4, 5],
       [7, 8]])

In [38]:
ar = np.array([1,2,3,4,6,8,10])

In [39]:
ar*2

array([ 2,  4,  6,  8, 12, 16, 20])

In [40]:
ar > 3

array([False, False, False,  True,  True,  True,  True])

In [41]:
bools = ar >3

In [42]:
bools

array([False, False, False,  True,  True,  True,  True])

In [43]:
ar[bools]

array([ 4,  6,  8, 10])

In [45]:
ar[ar>3]

array([ 4,  6,  8, 10])

In [46]:
ar[ar*2]

IndexError: index 8 is out of bounds for axis 0 with size 7